### ISSUE TITLE
[OSX] OSX image outdated and pip not installed?

### ISSUE THREAD

**Issue by Miniontoby** [batonogov/docker-pyinstaller#153]
**Describe the bug**
I tried to use the osx image to build my project in my cross-platform gitlab-ci, but it gave me the error that `pip` isn't installed.

I also noticed that the image is last updated 10 months ago

**To Reproduce**
1. Create a .gitlab-ci.yml (or just do a Dockerfile)
```yml
variables:
  PYTHON_VERSION: "3.10"
  BUILD_DIR: "build"
  DIST_DIR: "dist"
  RELEASE_DATE: $(date +'%Y-%m-%d %H:%M:%S')
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases"
  DEFAULT_ARGUMENTS_PYINSTALLER: "--onefile --windowed --clean --path $CI_PROJECT_DIR/$PROJECT --distpath $CI_PROJECT_DIR/$PROJECT/$DIST_DIR --workpath $CI_PROJECT_DIR/$PROJECT/$BUILD_DIR --hidden-import mysql.connector.locales.eng"

build_osx:
  stage: build
  image:
    name: batonogov/pyinstaller-osx:latest
    entrypoint: ['']
  variables:
    OS: 'osx'
    PROJECT: 'Test'
  before_script:
    - pip install -r ./$PROJECT/requirements.txt
  script:
    - cd ./$PROJECT && pyinstaller $DEFAULT_ARGUMENTS_PYINSTALLER main.py
  after_script:
    - echo "JOB_${PROJECT}_${OS}_ID=$CI_JOB_ID" | tee -a $GITLAB_ENV >> $CI_PROJECT_DIR/job.env
  artifacts:
    paths:
      - ./$PROJECT/$DIST_DIR/*
    reports:
      dotenv: job.env
```
2. Run the gitlab-ci or run dockerfile
3. See it fail

**Expected behavior**
I expected the image to create a binary, like with windows and linux

**Screenshots**
```
Running with gitlab-runner 18.0.2 (4d7093e1)
  on [redacted] [redacted], system ID: [redacted]
Preparing the "docker" executor
00:02
Using Docker executor with image batonogov/pyinstaller-osx:latest ...
Using effective pull policy of [always] for container batonogov/pyinstaller-osx:latest
Pulling docker image batonogov/pyinstaller-osx:latest ...
Using docker image sha256:96f5da5cf34f161228c4924d9657847fb236327a4f8fc4abe97465379fc0b8f3 for batonogov/pyinstaller-osx:latest with digest batonogov/pyinstaller-osx@sha256:fffe1e8f0cfa1c51f2c513d54229a507e082739461266d5330c6ae4b22dab11f ...
Preparing environment
00:00
Using effective pull policy of [always] for container sha256:579760f878b556eb21b01a4dd535c3b9142e5bce0843573db2764db8d7a8e02c
Running on runner-[redacted]-project-[redacted]-concurrent-0 via [redacted]...
Getting source from Git repository
00:00
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/[redacted]/.git/
Created fresh repository.
Checking out e374ec44 as detached HEAD (ref is feature-gitlab-releases)...
Removing Test/build/
Removing Test/dist/
Removing Test/main.spec
Removing job.env
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
Using effective pull policy of [always] for container batonogov/pyinstaller-osx:latest
Using docker image sha256:96f5da5cf34f161228c4924d9657847fb236327a4f8fc4abe97465379fc0b8f3 for batonogov/pyinstaller-osx:latest with digest batonogov/pyinstaller-osx@sha256:fffe1e8f0cfa1c51f2c513d54229a507e082739461266d5330c6ae4b22dab11f ...
$ pip install -r ./$PROJECT/requirements.txt
/usr/bin/bash: line 162: pip: command not found
Running after_script
00:00
Running after script...
$ echo "JOB_${PROJECT}_${OS}_ID=$CI_JOB_ID" | tee -a $GITLAB_ENV >> $CI_PROJECT_DIR/job.env
Uploading artifacts for failed job
00:00
Uploading artifacts...
job.env: found 1 matching artifact files and directories 
Uploading artifacts as "dotenv" to coordinator... 201 Created  id=13010 responseStatus=201 Created token=[redacted]-
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

Specifically `/usr/bin/bash: line 162: pip: command not found`

**Docker information (please provide the following information):**
- Docker image: `batonogov/pyinstaller-osx:latest`
- Docker version: ``
- Run command: `None`, running gitlab-ci
