### ISSUE TITLE
How to use it in Gitlab CI

### ISSUE THREAD

**Issue by etienne-monier** [batonogov/docker-pyinstaller#30]
Hi!

I'm using your script in Gitlab CI (thanks for the job!) and I'm facing an unexpected issue.

I'm using this job definition (not so needed for what's comming)
```
executable:
  stage: deploy
  image: batonogov/pyinstaller-linux:python-3.10
  variables:
    SRCDIR: $CI_PROJECT_DIR
    PYPI_URL: $ARTIFACTORY_PIP
    PYPI_INDEX_URL: ${ARTIFACTORY_PIP}/simple
  script:
    - echo "running"
  rules:
    - when: always
```

Yet, the gitlab runner provides arguments to entrypoint to manage the script section (see [Arguments passed via an entrypoint are going to be overridden by gitlab runner](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27706)). This is a long script to search for the shell executable to be used.

Running a job with the above configuration fails as the entrypoint script uses this if-statement scripts as an entrypoint argument instead of detecting no argument. It results the entrypoint script fails.

To solve that, I needed to disable the entrypoint and run the script myself.
```
executable:
  stage: deploy
  image:
    name: batonogov/pyinstaller-linux:python-3.10
    entrypoint: [""]
  variables:
    SRCDIR: $CI_PROJECT_DIR
    PYPI_URL: $ARTIFACTORY_PIP
    PYPI_INDEX_URL: ${ARTIFACTORY_PIP}/simple
  script:
    - /bin/sh -c /entrypoint.sh
  rules:
    - when: always
```

This is a minor problem as the workaround exists and is simple (but it took me some time to understand the problem).

I can't see a simple solution. Maybe provide the pyinstaller command as an env variable? Or first run the image with no entrypoint and then use `docker exec` to build the executable.

Have a nice day!

**Comment by batonogov** [comment]
Good afternoon.
Thanks for your feedback.
I'll think about how to solve your problem!

**Comment by batonogov** [comment]
Changed ENTROPOINT to CMD.

Your pipeline doesn't crash:

```zsh
executable:
   stage: deploy
   image: batonogov/pyinstaller-linux:gitlab_ci
   script:
     -ls -lh
     - echo "running"
   rules:
     - when: always
   allow_failure: false
```

Please try it and write your comment.

**Comment by vvyushmanov** [comment]
@batonogov Hello!

I tried the pyinstaller-windows:gitlab_ci image, and it seems to be working in terms of overriding the entrypoint, but the pyinstaller itself gave me errors.
Could you please merge the "latest" to "gitlab_ci" so that I can check?

Currently what worked for me was basically decomposing the entrypoint.sh script and putting the necessary steps to the CI job script:

```yaml
windows_bin:
  stage: artifacts
  image: 
    name: batonogov/pyinstaller-windows:latest
    entrypoint: [""]
  variables:
    SRCDIR: $CI_PROJECT_DIR
  rules:
    - if: $CI_COMMIT_TAG =~ /[0-9]+\.[0-9]+\.[0-9]+/ || $TEST_BUILD == "true"
  script:
    - echo "Creating Windows artifact"
    - . /root/.bashrc
    - pip install -r requirements.txt
    - pyinstaller --onedir main.py --uac-admin --add-binary adb/adb.exe:adb --distpath dist/Windows -n T.Nebula --noconfirm --hide-console minimize-early --add-data Tassta-chan.png:. --add-data t-nebula.ico:. --icon t-nebula.ico --add-binary adb/AdbWinUsbApi.dll:adb --add-binary adb/AdbWinApi.dll:adb --clean
    - mv ./dist/Windows/T.Nebula/ ./T.Nebula/
    - echo "WIN_JOB=${CI_JOB_ID}" >> build.env
  artifacts:
    name: "t.nebula-win_x64-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - "./T.Nebula/*"
    reports:
      dotenv: build.env
```

When I was trying to launch it through the entrypoint, however, I was getting pyinstaller errors, claiming there's no main.py script (looks like the SRCDIR was not passed correctly).

Also, could ou please update the README to reflect the environment variable usage? Currently they are only described in the script body.
